# A Travis is a service that provides Continuous Integration (CI) freely for
# Open-Source projects.
# It can be integrated with GitHub, by making a build each time new code is pushed.
# This is also done with PRs (Pull Requests), which can be rejected if failing the builds.

# Specify we are working with a Java project.
# Travis can be used also for many other languages.
language: java

# The JDK we need for compiling
jdk:
  - openjdk11


# As the build will download JAR files from Maven Central, optimize their storage,
# so they do not get re-downloaded each time
cache:
  directories:
  - .autoconf
  - $HOME/.m2

# Useful when working in team. If someone breaks the build (code does not compile
# or some tests are failing), then get notified by email immediately.
notifications:
  email: true


# The actual command we do for compiling.
# Note: Travis has a quite limited handling of build log files, so need
# to minimize them, ie do not be too verbose
script: mvn clean verify  --quiet

# Note: in Continuous Delivery, we could do a "mvn deploy" here to automatically
# deploy the artifacts if build is successful.
# So that you can do deployment by just doing a Git Push.
# However, in such case, best to have a special Git Branch for it, and
# not the master one.
#
# Note: the status of Travis build can also be put on the README.md as an
# image linked from Travis